### ISSUE TITLE
PgSQL timestamp support

### ISSUE THREAD

**Issue by galeaspablo** [ambarltd/emulator#27]
Pg timestamps can't be read by the emulator. Please fix. Ie we need to support both timestamp and timestamptz.

```
configuration loaded
src: event_with_datetime_2 | connected
emulator: Incompatible {errSQLType = "timestamp", errSQLTableOid = Just (Oid 16416), errSQLField = "occurred_on", errHaskellType = "Text", errMessage = "types incompatible"}
HasCallStack backtrace:
  collectBacktraces, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:92:13 in ghc-internal:GHC.Internal.Exception
  toExceptionWithBacktrace, called at libraries/ghc-internal/src/GHC/Internal/IO.hs:260:11 in ghc-internal:GHC.Internal.IO
  throwIO, called at libraries/ghc-internal/src/GHC/Internal/Control/Exception/Base.hs:195:43 in ghc-internal:GHC.Internal.Control.Exception.Base
```

Keep in mind that in the cloud version we support both timestamp and timestampz, and we format both in ISO8601 format, which supports having a timezone or not. Please make sure you don't send a timezone for timestamp. 

Our PG connector asks PG to give the date in ISO8601 format by setting up the format in the session itself

https://github.com/ambarltd/connector_postgresql/blob/main/main.c#L2839C21-L2839C45

**Comment by lazamar** [comment]
Fixed by #29
